# Generated by Django 5.2 on 2025-08-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark Theme'), ('light', 'Light Theme')], default='dark', max_length=10),
        ),
    ]
