# Generated by Django 5.2 on 2025-08-07 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-date_action']},
        ),
        migrations.RemoveField(
            model_name='log',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='rapportenvoye',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='log',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='log',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='log',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapportenvoye',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('create', 'Create Record'), ('update', 'Update Record'), ('delete', 'Delete Record'), ('view', 'View Record'), ('export', 'Export Data'), ('import', 'Import Data'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update'), ('theme_change', 'Theme Change'), ('report_sent', 'Report Sent'), ('stock_alert', 'Stock Alert'), ('system', 'System Action')], max_length=50),
        ),
        migrations.AlterField(
            model_name='log',
            name='id_element',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='table_cible',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
