# Generated by Django 4.2.23 on 2025-08-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_log_options_remove_log_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('auto_logout', 'Auto Logout'), ('create', 'Create Record'), ('update', 'Update Record'), ('delete', 'Delete Record'), ('view', 'View Record'), ('export', 'Export Data'), ('import', 'Import Data'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update'), ('theme_change', 'Theme Change'), ('report_sent', 'Report Sent'), ('stock_alert', 'Stock Alert'), ('system', 'System Action')], max_length=50),
        ),
    ]
