# Generated by Django 5.2 on 2025-09-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_produit_description_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
