# Generated by Django 4.2.23 on 2025-09-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reservation_prix'),
        ('core', '0007_userprofile_avatar'),
    ]

    operations = [
    ]
