<<<<<<< HEAD
# Generated by Django 4.2.23 on 2025-09-08 13:55
=======
# Generated by Django 5.2 on 2025-09-08 13:36
>>>>>>> d6b252ee08290b7800eddd30e31e6907c051cb0e

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reservation_prix'),
        ('core', '0007_userprofile_avatar'),
    ]

    operations = [
    ]
