# Generated by Django 4.2.23 on 2025-09-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_0007_reservation_prix_0007_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
