# Generated by Django 5.2 on 2025-09-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
